export type EmergencyServiceType = "hospital" | "police" | "fire_station" | "clinic";

export interface EmergencyService {
  id: string;
  name: string;
  shortName: string;
  type: EmergencyServiceType;
  category: string;
  lat: number;
  lng: number;
  address: string;
  district: string;
  city: string;
  phone: string;
  emergency?: string;
  status: "active" | "standby" | "alert";
  hours: string;
  beds?: number;
  vehicles?: string;
  fleet?: string;
}

export const TALLINN_EMERGENCY_SERVICES: EmergencyService[] = [
  // Hospitals & Critical Care
  {
    id: "hosp-perh",
    name: "Põhja-Eesti Regionaalhaigla (PERH)",
    shortName: "PERH EMO",
    type: "hospital",
    category: "Regional Trauma Center & Emergency",
    lat: 59.3970,
    lng: 24.6980,
    address: "J. Sütiste tee 19",
    district: "Mustamäe",
    city: "Tallinn",
    phone: "+372 617 1300",
    emergency: "112",
    status: "active",
    hours: "24/7 EMO Open",
    beds: 1200,
  },
  {
    id: "hosp-itk",
    name: "Ida-Tallinna Keskhaigla (ITK)",
    shortName: "ITK Ravi üksus",
    type: "hospital",
    category: "Central Hospital & Inpatient",
    lat: 59.4282,
    lng: 24.7570,
    address: "Ravi tn 18",
    district: "Kesklinn",
    city: "Tallinn",
    phone: "+372 666 1900",
    emergency: "112",
    status: "active",
    hours: "24/7 EMO Open",
    beds: 650,
  },
  {
    id: "hosp-ltkh",
    name: "Lääne-Tallinna Keskhaigla (LTKH)",
    shortName: "LTKH Meremeeste",
    type: "hospital",
    category: "West Tallinn Central Hospital",
    lat: 59.4355,
    lng: 24.7042,
    address: "Paldiski mnt 68",
    district: "Põhja-Tallinn",
    city: "Tallinn",
    phone: "+372 626 1314",
    emergency: "112",
    status: "active",
    hours: "24/7 EMO Open",
    beds: 520,
  },
  {
    id: "hosp-laste",
    name: "Tallinna Lastehaigla",
    shortName: "Lastehaigla",
    type: "hospital",
    category: "Pediatric Hospital & Child Trauma",
    lat: 59.3944,
    lng: 24.6975,
    address: "Tervise tn 28",
    district: "Mustamäe",
    city: "Tallinn",
    phone: "+372 697 7140",
    emergency: "112",
    status: "active",
    hours: "24/7 Children ER",
    beds: 350,
  },
  {
    id: "hosp-magdaleena",
    name: "ITK Magdaleena Tervisemaja",
    shortName: "ITK Magdaleena",
    type: "clinic",
    category: "Diagnostic Center & Outpatient",
    lat: 59.4124,
    lng: 24.7352,
    address: "Pärnu mnt 104",
    district: "Kesklinn",
    city: "Tallinn",
    phone: "+372 666 1900",
    emergency: "112",
    status: "active",
    hours: "Mon-Fri 08:00-19:00",
  },
  {
    id: "hosp-pelgulinna",
    name: "Pelgulinna Sünnitusmaja",
    shortName: "Pelgulinna EMO",
    type: "hospital",
    category: "Maternity & Neonatal Care",
    lat: 59.4440,
    lng: 24.7128,
    address: "Sõle tn 23",
    district: "Põhja-Tallinn",
    city: "Tallinn",
    phone: "+372 666 5700",
    emergency: "112",
    status: "active",
    hours: "24/7 Open",
  },
  {
    id: "hosp-kiirabi-hq",
    name: "Tallinna Kiirabi Peamaja",
    shortName: "Tallinna Kiirabi HQ",
    type: "hospital",
    category: "Emergency Medical Response Fleet",
    lat: 59.4005,
    lng: 24.7020,
    address: "Retke tee 1",
    district: "Mustamäe",
    city: "Tallinn",
    phone: "+372 697 1100",
    emergency: "112",
    status: "active",
    hours: "24/7 Mobile Response",
    fleet: "42 Ambulances",
  },
  {
    id: "hosp-confido",
    name: "Confido Meditsiinikeskus",
    shortName: "Confido Medical",
    type: "clinic",
    category: "Private Healthcare & Urgent Care",
    lat: 59.4208,
    lng: 24.7548,
    address: "Veerenni tn 51",
    district: "Kesklinn",
    city: "Tallinn",
    phone: "+372 1330",
    status: "active",
    hours: "08:00-21:00",
  },
  {
    id: "clinic-mustamae",
    name: "Mustamäe Tervisekeskus",
    shortName: "Mustamäe Tervis",
    type: "clinic",
    category: "Primary Health Center",
    lat: 59.4042,
    lng: 24.6644,
    address: "Ehitajate tee 27",
    district: "Mustamäe",
    city: "Tallinn",
    phone: "+372 659 8000",
    status: "active",
    hours: "08:00-18:00",
  },
  {
    id: "clinic-lasnamae",
    name: "Lasnamäe Tervisemaja",
    shortName: "Lasnamäe Tervis",
    type: "clinic",
    category: "Primary Health Center",
    lat: 59.4501,
    lng: 24.8720,
    address: "Linnamäe tee 3",
    district: "Lasnamäe",
    city: "Tallinn",
    phone: "+372 605 0601",
    status: "active",
    hours: "08:00-19:00",
  },

  // Police & Law Enforcement
  {
    id: "pol-ppa-hq",
    name: "Politsei- ja Piirivalveameti Peamaja (PPA HQ)",
    shortName: "PPA Peamaja",
    type: "police",
    category: "National Police Headquarters",
    lat: 59.4082,
    lng: 24.7380,
    address: "Pärnu mnt 139",
    district: "Kesklinn",
    city: "Tallinn",
    phone: "+372 612 3000",
    emergency: "112",
    status: "active",
    hours: "24/7 Operations Command",
  },
  {
    id: "pol-kesklinn",
    name: "Põhja Prefektuur / Kesklinna jaoskond",
    shortName: "PPA Kesklinn",
    type: "police",
    category: "Regional Police Station",
    lat: 59.4418,
    lng: 24.6985,
    address: "Kolde pst 65",
    district: "Põhja-Tallinn",
    city: "Tallinn",
    phone: "+372 612 5400",
    emergency: "112",
    status: "active",
    hours: "24/7 Active Patrols",
  },
  {
    id: "pol-rahumae",
    name: "PPA Lõuna politseijaoskond",
    shortName: "PPA Rahumäe",
    type: "police",
    category: "Police Precinct & Rapid Response",
    lat: 59.4012,
    lng: 24.7150,
    address: "Rahumäe tee 6",
    district: "Kristiine",
    city: "Tallinn",
    phone: "+372 612 5600",
    emergency: "112",
    status: "active",
    hours: "24/7 Active Patrols",
  },
  {
    id: "pol-ida-harju",
    name: "PPA Ida-Harju politseijaoskond",
    shortName: "PPA Lasnamäe",
    type: "police",
    category: "Police Precinct & Patrol Fleet",
    lat: 59.4348,
    lng: 24.8450,
    address: "P. Pinna tn 4",
    district: "Lasnamäe",
    city: "Tallinn",
    phone: "+372 612 4800",
    emergency: "112",
    status: "active",
    hours: "24/7 Active Patrols",
  },
  {
    id: "pol-laane-harju",
    name: "PPA Lääne-Harju politseijaoskond",
    shortName: "PPA Mustamäe",
    type: "police",
    category: "Police Precinct & Traffic Supervision",
    lat: 59.4140,
    lng: 24.6540,
    address: "Ehitajate tee 109a",
    district: "Mustamäe",
    city: "Tallinn",
    phone: "+372 612 5700",
    emergency: "112",
    status: "active",
    hours: "24/7 Active Patrols",
  },
  {
    id: "pol-mupo",
    name: "Tallinna Munitsipaalpolitsei Amet (MUPO)",
    shortName: "MUPO HQ",
    type: "police",
    category: "Municipal Law Enforcement",
    lat: 59.4340,
    lng: 24.7170,
    address: "Paldiski mnt 48a",
    district: "Põhja-Tallinn",
    city: "Tallinn",
    phone: "+372 661 9860",
    emergency: "14410",
    status: "active",
    hours: "24/7 Municipal Patrol",
  },
  {
    id: "pol-airport",
    name: "PPA Lennujaama Piiripunkt",
    shortName: "PPA Airport Border",
    type: "police",
    category: "Border Guard & Airport Security",
    lat: 59.4132,
    lng: 24.8010,
    address: "Tartu mnt 101",
    district: "Lasnamäe",
    city: "Tallinn",
    phone: "+372 605 8400",
    status: "active",
    hours: "24/7 Security",
  },
  {
    id: "pol-port",
    name: "PPA Vanasadama Piiripunkt",
    shortName: "PPA Harbour Border",
    type: "police",
    category: "Border Guard & Port Security",
    lat: 59.4445,
    lng: 24.7610,
    address: "Sadama tn 25",
    district: "Kesklinn",
    city: "Tallinn",
    phone: "+372 661 6300",
    status: "active",
    hours: "24/7 Port Security",
  },

  // Fire & Rescue Services (Päästeamet)
  {
    id: "fire-kesklinn",
    name: "Kesklinna Päästekomando & Päästeamet HQ",
    shortName: "Kesklinna Pääste",
    type: "fire_station",
    category: "Rescue & Fire Brigade Command",
    lat: 59.4358,
    lng: 24.7675,
    address: "Raua tn 2",
    district: "Kesklinn",
    city: "Tallinn",
    phone: "+372 628 2000",
    emergency: "112",
    status: "active",
    hours: "24/7 Emergency Ready",
    vehicles: "3 Engines, 1 Ladder",
  },
  {
    id: "fire-lillekula",
    name: "Lilleküla Päästekomando",
    shortName: "Lilleküla Pääste",
    type: "fire_station",
    category: "Rescue & Fire Brigade",
    lat: 59.4328,
    lng: 24.7115,
    address: "Paldiski mnt 47",
    district: "Kristiine",
    city: "Tallinn",
    phone: "+372 628 2150",
    emergency: "112",
    status: "active",
    hours: "24/7 Emergency Ready",
    vehicles: "2 Engines, 1 Tanker",
  },
  {
    id: "fire-nomme",
    name: "Nõmme Päästekomando",
    shortName: "Nõmme Pääste",
    type: "fire_station",
    category: "Rescue & Fire Brigade",
    lat: 59.3888,
    lng: 24.6885,
    address: "Jaama tn 2",
    district: "Nõmme",
    city: "Tallinn",
    phone: "+372 628 2200",
    emergency: "112",
    status: "active",
    hours: "24/7 Emergency Ready",
    vehicles: "2 Engines",
  },
  {
    id: "fire-mustamae",
    name: "Mustamäe Päästekomando",
    shortName: "Mustamäe Pääste",
    type: "fire_station",
    category: "Rescue & Fire Brigade",
    lat: 59.3905,
    lng: 24.6590,
    address: "Akadeemia tee 50",
    district: "Mustamäe",
    city: "Tallinn",
    phone: "+372 628 2250",
    emergency: "112",
    status: "active",
    hours: "24/7 Emergency Ready",
    vehicles: "2 Engines, 1 Heavy Rescue",
  },
  {
    id: "fire-pirita",
    name: "Pirita Päästekomando",
    shortName: "Pirita Pääste",
    type: "fire_station",
    category: "Rescue, Water Rescue & Fire Brigade",
    lat: 59.4695,
    lng: 24.8690,
    address: "Kloostrimetsa tee 56",
    district: "Pirita",
    city: "Tallinn",
    phone: "+372 628 2300",
    emergency: "112",
    status: "active",
    hours: "24/7 Marine & Fire Ready",
    vehicles: "2 Engines, 2 Rescue Boats",
  },
  {
    id: "fire-lasnamae",
    name: "Lasnamäe Päästekomando",
    shortName: "Lasnamäe Pääste",
    type: "fire_station",
    category: "Rescue & Fire Brigade",
    lat: 59.4335,
    lng: 24.8785,
    address: "Osmussaare tn 2",
    district: "Lasnamäe",
    city: "Tallinn",
    phone: "+372 628 2350",
    emergency: "112",
    status: "active",
    hours: "24/7 Emergency Ready",
    vehicles: "3 Engines, 1 Ladder",
  },
  {
    id: "fire-kopli",
    name: "Kopli Päästekomando",
    shortName: "Kopli Pääste",
    type: "fire_station",
    category: "Port & Hazmat Fire Brigade",
    lat: 59.4580,
    lng: 24.6890,
    address: "Ankru tn 12",
    district: "Põhja-Tallinn",
    city: "Tallinn",
    phone: "+372 628 2400",
    emergency: "112",
    status: "active",
    hours: "24/7 Emergency Ready",
    vehicles: "2 Engines, Hazmat Unit",
  },
];
