export type TransportHubType = "airport" | "heliport" | "railway" | "port";

export interface TransportHub {
  id: string;
  name: string;
  nameEn?: string;
  shortName: string;
  type: TransportHubType;
  category: string;
  lat: number;
  lng: number;
  address: string;
  district: string;
  city: string;
  phone?: string;
  website?: string;
  status: "active" | "busy" | "alert";
  passengerVolume: string;
  dailyPassengers?: number;
  cargoVolume?: string;
  activeLinesOrTerminals: string[];
  activeTerminalCount?: number;
  description: string;
}

export const TALLINN_TRANSPORT_HUBS: TransportHub[] = [
  // --- AIRPORTS & HELIPORTS ---
  {
    id: "hub-tll-airport",
    name: "Tallinn Lennart Meri Airport",
    nameEn: "Tallinn International Airport",
    shortName: "TLL Airport",
    type: "airport",
    category: "International Passenger & Cargo Airport",
    lat: 59.4132,
    lng: 24.8326,
    address: "Tartu mnt 101",
    district: "Lasnamäe / Ülemiste",
    city: "Tallinn",
    phone: "+372 614 0000",
    website: "https://tallinn-airport.ee",
    status: "active",
    passengerVolume: "~9,500 / day",
    cargoVolume: "35,000 tons / yr",
    activeLinesOrTerminals: ["Terminal 1 Main", "Cargo Gate East", "VIP Terminal", "Helipad A1"],
    description: "Primary international airport of Estonia. Connects Tallinn to 40+ European hubs with full modern radar integration.",
  },
  {
    id: "hub-linnahall-heliport",
    name: "Tallinn Linnahall Heliport",
    nameEn: "City Maritime Heliport",
    shortName: "City Heliport",
    type: "heliport",
    category: "Commercial & Emergency Heliport",
    lat: 59.4479,
    lng: 24.7533,
    address: "Mere pst 20 / Logi 6",
    district: "Kesklinn / Sadama",
    city: "Tallinn",
    phone: "+372 611 6000",
    status: "active",
    passengerVolume: "~150 / day",
    activeLinesOrTerminals: ["Helipad 1 (Primary)", "Emergency Medevac Pad"],
    description: "Maritime and coastal helipad facility utilized for fast offshore, VIP, and emergency medevac operations.",
  },
  {
    id: "hub-amari-airfield",
    name: "Ämari Logistics Airfield",
    nameEn: "Ämari Auxiliary Air Base",
    shortName: "Ämari Base",
    type: "airport",
    category: "Regional Cargo & Flight Logistics Base",
    lat: 59.2622,
    lng: 24.2186,
    address: "Ämari, Harju County",
    district: "Lääne-Harju",
    city: "Ämari",
    status: "active",
    passengerVolume: "Military / Special Cargo",
    cargoVolume: "12,000 tons / yr",
    activeLinesOrTerminals: ["Runway 06/24", "Cargo Hangar Alpha"],
    description: "Logistical auxiliary airfield serving western Harju regional operations and strategic transport.",
  },

  // --- RAILWAY STATIONS & TRAIN HUBS ---
  {
    id: "hub-balti-jaam",
    name: "Balti Jaam (Tallinn Central Station)",
    nameEn: "Baltic Passenger Railway Station",
    shortName: "Balti Jaam",
    type: "railway",
    category: "Central Passenger Railway Station",
    lat: 59.4402,
    lng: 24.7378,
    address: "Toompuiestee 37 / Kopli 1",
    district: "Põhja-Tallinn / Kalamaja",
    city: "Tallinn",
    phone: "+372 616 0000",
    website: "https://elron.ee",
    status: "busy",
    passengerVolume: "~22,000 / day",
    activeLinesOrTerminals: ["Elron West Line", "Elron East Line", "Elron South Line", "Tram Lines 1, 2, 5"],
    description: "The main passenger railway hub of Tallinn connecting regional commuter trains and international passenger routes.",
  },
  {
    id: "hub-ulemiste-rail",
    name: "Ülemiste Railway & Rail Baltica Hub",
    nameEn: "Ülemiste Multimodal Express Terminal",
    shortName: "Ülemiste Stn",
    type: "railway",
    category: "High-Speed Rail & Commuter Junction",
    lat: 59.4233,
    lng: 24.7961,
    address: "Suur-Sõjamäe 4",
    district: "Lasnamäe / Ülemiste",
    city: "Tallinn",
    status: "active",
    passengerVolume: "~14,000 / day",
    activeLinesOrTerminals: ["Rail Baltica Express Terminal", "Tartu Line", "Narva Express", "Airport Tram Link 4"],
    description: "Major multimodal transit hub linking Tallinn Airport, national express rail lines, and future Rail Baltica international corridor.",
  },
  {
    id: "hub-tondi-rail",
    name: "Tondi Commuter Rail Station",
    nameEn: "Tondi Railway Stop",
    shortName: "Tondi Stn",
    type: "railway",
    category: "Urban Rail Intermodal Stop",
    lat: 59.4114,
    lng: 24.7338,
    address: "Tondi tn (Tondi Viadukt)",
    district: "Kristiine",
    city: "Tallinn",
    status: "active",
    passengerVolume: "~4,500 / day",
    activeLinesOrTerminals: ["Keila / Paldiski Line", "Tram 3, 4 Loop"],
    description: "Crucial commuter transfer point between Paldiski/Keila rail lines and inner-city tram routes.",
  },
  {
    id: "hub-nomme-rail",
    name: "Nõmme Railway Station",
    nameEn: "Nõmme Suburban Station",
    shortName: "Nõmme Stn",
    type: "railway",
    category: "Suburban Commuter Station",
    lat: 59.3862,
    lng: 24.6868,
    address: "Jaama 18",
    district: "Nõmme",
    city: "Tallinn",
    status: "active",
    passengerVolume: "~3,200 / day",
    activeLinesOrTerminals: ["Pääsküla Commuter", "Riisipere Line"],
    description: "Historic suburban rail depot serving southern districts of Tallinn with frequent commuter frequency.",
  },

  // --- PORTS & HARBOURS ---
  {
    id: "hub-vanasadam-port",
    name: "Old City Harbour (Tallinna Vanasadam)",
    nameEn: "Passenger Sea Port of Tallinn",
    shortName: "Vanasadam Port",
    type: "port",
    category: "International Passenger Ferry & Cruise Port",
    lat: 59.4449,
    lng: 24.7608,
    address: "Sadama 25",
    district: "Kesklinn / Sadama",
    city: "Tallinn",
    phone: "+372 631 8555",
    website: "https://ts.ee",
    status: "busy",
    passengerVolume: "~28,000 / day",
    cargoVolume: "Ro-Ro Vehicle Traffic",
    activeLinesOrTerminals: ["Terminal A (Helsinki)", "Terminal D (Helsinki/Stockholm)", "Cruise Promenade Quay"],
    description: "One of the busiest passenger sea ports on the Baltic Sea. Hosts daily heavy ferry liners (Tallink, Viking Line, Eckerö Line).",
  },
  {
    id: "hub-muuga-port",
    name: "Port of Muuga (Muuga Sadam)",
    nameEn: "Deepwater Cargo Port",
    shortName: "Muuga Port",
    type: "port",
    category: "Industrial Deepwater Cargo & Container Port",
    lat: 59.4960,
    lng: 24.9600,
    address: "Maardu tee 57, Maardu",
    district: "Viimsi / Maardu",
    city: "Tallinn Suburbs",
    phone: "+372 631 9500",
    status: "active",
    passengerVolume: "Cargo & Logistics Personnel",
    cargoVolume: "20.5M tons / yr",
    activeLinesOrTerminals: ["Container Terminal 1", "Oil & Chemical Quay B", "Ro-Ro Rail Terminal"],
    description: "Estonia's largest cargo port handling containers, bulk cargo, petroleum products, and heavy maritime logistics.",
  },
  {
    id: "hub-paljassaare-port",
    name: "Paljassaare Harbour & Hundipea Port",
    nameEn: "Paljassaare Timber & Industrial Port",
    shortName: "Paljassaare Port",
    type: "port",
    category: "Maritime Industrial & Timber Port",
    lat: 59.4583,
    lng: 24.7067,
    address: "Paljassaare tee 28",
    district: "Põhja-Tallinn",
    city: "Tallinn",
    status: "active",
    passengerVolume: "~300 / day",
    cargoVolume: "3.2M tons / yr",
    activeLinesOrTerminals: ["Timber Quay 3", "Oil Pier West", "Fishing Dock North"],
    description: "Industrial port complex in Northern Tallinn specialized in timber, oil products, and maritime services.",
  },
  {
    id: "hub-bekker-port",
    name: "Bekker & Meeruse Harbour",
    nameEn: "Bekker Shipyard & Commercial Port",
    shortName: "Bekker Port",
    type: "port",
    category: "Private Bulk Cargo & Shipyard Port",
    lat: 59.4539,
    lng: 24.6675,
    address: "Kopli 103",
    district: "Põhja-Tallinn / Kopli",
    city: "Tallinn",
    status: "active",
    passengerVolume: "Industrial Crew",
    cargoVolume: "1.8M tons / yr",
    activeLinesOrTerminals: ["Bekker Cargo Berth 1", "Meeruse Slipway"],
    description: "Protected West Tallinn harbour handling general cargo, building materials, and vessel refitting operations.",
  }
];
